# Generated by Django 5.0.1 on 2024-02-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='roomtesti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images\\Room')),
            ],
        ),
        migrations.AlterField(
            model_name='explore',
            name='image',
            field=models.ImageField(upload_to='images\\Service'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to='images\\Team'),
        ),
    ]
