# Generated by Django 5.0.1 on 2024-02-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_roomtesti_alter_explore_image_alter_team_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='roomtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images\\Rooms')),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=50)),
                ('beds', models.IntegerField(max_length=10)),
                ('bath', models.IntegerField(max_length=10)),
                ('wifi', models.IntegerField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
