# Generated by Django 5.0.1 on 2024-02-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_roomtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='abouttesti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/About')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='bath',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='beds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='wifi',
            field=models.CharField(max_length=10),
        ),
    ]
