# Generated by Django 5.0.1 on 2024-02-23 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_bookingdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bookingdetail',
            new_name='Bookingdetailform',
        ),
    ]
