# Generated by Django 5.0.1 on 2024-02-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_rename_bookingdetail_bookingdetailform'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null='True')),
                ('email', models.EmailField(max_length=254)),
                ('checkin', models.DateTimeField()),
                ('checkout', models.DateTimeField()),
                ('adultnum', models.IntegerField()),
                ('childnum', models.IntegerField()),
                ('roomnum', models.IntegerField()),
                ('request', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Bookingdetailform',
        ),
    ]
