# Generated by Django 5.0.1 on 2024-02-26 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_bookingdetail_delete_bookingdetailform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bookingdetail',
            new_name='bookingdetailform',
        ),
    ]
