# Generated by Django 5.0.1 on 2024-02-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_alter_bookingdetailform_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetailform',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
    ]
