# Generated by Django 5.0.1 on 2024-02-26 09:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_alter_bookingdetailform_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetailform',
            name='checkout',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
