# Generated by Django 5.0.1 on 2024-02-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_alter_bookingdetailform_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetailform',
            name='childnum',
            field=models.IntegerField(null=True),
        ),
    ]
