# Generated by Django 5.0.1 on 2024-02-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_alter_bookingdetailform_childnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetailform',
            name='roomnum',
            field=models.IntegerField(null=True),
        ),
    ]
