# Generated by Django 5.0.1 on 2024-02-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_alter_bookingdetailform_roomnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetailform',
            name='request',
            field=models.TextField(null=True),
        ),
    ]
