# Generated by Django 5.0.1 on 2024-02-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_signupform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupform',
            name='contact',
            field=models.IntegerField(max_length=15, null=True),
        ),
    ]
