# Generated by Django 5.0.1 on 2024-02-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_alter_signupform_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupform',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
