# Generated by Django 5.0.1 on 2024-02-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_alter_signupform_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupform',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='signupform',
            name='repassword',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
