# Generated by Django 5.0.1 on 2024-03-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_userprofile_delete_signupform'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('date', models.DateField(null=True)),
                ('people', models.IntegerField(null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
