# Generated by Django 5.0.1 on 2024-03-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_bookingtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='roomno',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='timeslot',
            field=models.IntegerField(null=True),
        ),
    ]
