# Generated by Django 5.0.1 on 2024-03-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_bookingtable_roomno_bookingtable_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='cabform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('number', models.IntegerField()),
                ('airport', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='explore',
        ),
    ]
