# Generated by Django 5.0.1 on 2024-03-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_cabform_delete_explore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cabform',
            new_name='cabdetailform',
        ),
    ]
